export { default as Button } from './Button';
export { default as Input } from './Input';
export { default as PostItem } from './PostItem';
export { default as Snackbar } from './Snackbar';
export type { TSnackbarCategorie  } from './Snackbar';
export type { TBtnLink  } from './Button';
export { default as Passports } from './InputGroups/Passport';
export { default as BirthCertificate } from './InputGroups/BirthCertificate';
export { default as CNI } from './InputGroups/CNI';
export { default as GeneralObj } from './InputGroups/RandomObjects';
export { default as GeneralDocs } from './InputGroups/GeneralDocs';
export { default as Docs } from './InputGroups/Documents';